#define FIX(x) x
#define CREATE

#define INSERT_BEFORE_GETTING_STARTED(...)
#define INSERT_AT_GETTING_STARTED(...) __VA_ARGS__
#define INSERT_BEFORE_STATEMENTS(...)
#define INSERT_AT_STATEMENTS(...) __VA_ARGS__
#define INSERT_BEFORE_BUILDING(...)
#define INSERT_AT_BUILDING(...) __VA_ARGS__
#define INSERT_BEFORE_VARIABLES(...)
#define INSERT_AT_VARIABLES(...) __VA_ARGS__
#define INSERT_BEFORE_DIRECTIVES(...)
#define INSERT_AT_DIRECTIVES(...) __VA_ARGS__
#define INSERT_BEFORE_OBJECTS(...)
#define INSERT_AT_OBJECTS(...) __VA_ARGS__
#define INSERT_BEFORE_REFERENCES(...)
#define INSERT_AT_REFERENCES(...) __VA_ARGS__
#define INSERT_BEFORE_GRID(...)
#define INSERT_AT_GRID(...) __VA_ARGS__

// More Basics
#define INSERT_BEFORE_CONTROL_FLOW(...)
#define INSERT_AT_CONTROL_FLOW(...) __VA_ARGS__
#define INSERT_BEFORE_EXPRESSIONS(...)
#define INSERT_AT_EXPRESSIONS(...) __VA_ARGS__
#define INSERT_BEFORE_FUNCTIONS(...)
#define INSERT_AT_FUNCTIONS(...) __VA_ARGS__

#define INSERT_BEFORE_CRYPTOGRAPHY(...)
#define INSERT_AT_CRYPTOGRAPHY(...) __VA_ARGS__
